<template>
  <div>
    <p v-if="error" class="error">Error: {{ error }}</p>

    <qrcode-stream @decode="onDecode" @init="onInit">
      <div class="qr-border">
        <svg viewBox="0 0 100 100">
          <path
            d="M25,2 L2,2 L2,25"
            fill="none"
            stroke="black"
            stroke-width="1"
          />
          <path
            d="M2,75 L2,98 L25,98"
            fill="none"
            stroke="black"
            stroke-width="1"
          />
          <path
            d="M75,98 L98,98 L98,75"
            fill="none"
            stroke="black"
            stroke-width="1"
          />
          <path
            d="M98,25 L98,2 L75,2"
            fill="none"
            stroke="black"
            stroke-width="1"
          />
        </svg>
      </div>
    </qrcode-stream>
  </div>
</template>

<script>
import { QrcodeStream } from 'vue-qrcode-reader'
import { mapGetters } from 'vuex'

export default {
  components: { QrcodeStream },
  props: {
    scanningConfirmationCode: {
      type: Boolean,
      default: false
    },
    verifying: {
      type: Boolean,
      default: false
    }
  },
  data() {
    return {
      result: '',
      error: ''
    }
  },
  computed: {
    ...mapGetters('questions', ['getFormSteps']),
    ...mapGetters('patients', ['currentPatient'])
  },
  methods: {
    onDecode(result) {
      this.result = result

      let patient
      try {
        patient = JSON.parse(result)

        // Validate JSON schema
        const incommingKeys = Object.keys(patient)
        const requiredKeys = [
          'id',
          'firstName',
          'lastName',
          'birthNumber',
          'phoneNumber',
          'answers',
          'termsAccepted'
        ]
        if (this.scanningConfirmationCode || this.verifying)
          requiredKeys.push('signature')
        const optionalKeys = [
          'confirmation',
          'confirmed',
          'isCovidSuspected',
          'finished'
        ]

        requiredKeys.forEach(key => {
          if (incommingKeys.indexOf(key) === -1)
            throw Error(`Error: Missing key "${key}" in JSON`)
        })

        const incommingAnswers = Object.keys(patient.answers)
        const requiredAnswers = this.getFormSteps
          .map(step => step.order)
          .filter(stepNum => stepNum !== '0' && stepNum.length <= 1)

        requiredAnswers.forEach(answer => {
          if (incommingAnswers.indexOf(answer) === -1)
            throw Error(`Error: Missing answer "${answer}"  in JSON`)
        })

        // Remove keys, we don't need
        Object.keys(patient).forEach(key => {
          if (
            requiredKeys.indexOf(key) === -1 &&
            optionalKeys.indexOf(key) === -1
          )
            delete patient[key]
        })

        if (this.scanningConfirmationCode) {
          if (
            this.currentPatient.id !== patient.id ||
            this.currentPatient.firstName !== patient.firstName ||
            this.currentPatient.lastName !== patient.lastName ||
            this.currentPatient.birthNumber !== patient.birthNumber ||
            this.currentPatient.phoneNumber !== patient.phoneNumber
          ) {
            this.error =
              'You scanned an invalid code. Please make sure your are scanning for the correct patient and try again. If you have problems contact the hospital staff.'
          } else {
            // Emit valid patient object
            this.$emit('patient', patient)
          }
        } else {
          // Emit valid patient object
          this.$emit('patient', patient)
        }
      } catch (e) {
        this.error = `Error reading QR code! Make sure you are only reading QR codes generated by this app, your (and patient's) app is up to date. Then try again.`
        console.error(e)
      }
    },
    async onInit(promise) {
      try {
        await promise
      } catch (error) {
        if (error.name === 'NotAllowedError') {
          this.error = 'ERROR: you need to grant camera access permisson'
        } else if (error.name === 'NotFoundError') {
          this.error = 'ERROR: no camera on this device'
        } else if (error.name === 'NotSupportedError') {
          this.error = 'ERROR: secure context required (HTTPS, localhost)'
        } else if (error.name === 'NotReadableError') {
          this.error = 'ERROR: is the camera already in use?'
        } else if (error.name === 'OverconstrainedError') {
          this.error = 'ERROR: installed cameras are not suitable'
        } else if (error.name === 'StreamApiNotSupportedError') {
          this.error = 'ERROR: Stream API is not supported in this browser'
        }
      }
    }
  }
}
</script>

<style scoped lang="scss">
.error {
  font-weight: bold;
  color: red;
}

.qr-border {
  height: 100%;
  width: 100%;
  display: flex;
  justify-content: center;
  align-items: center;

  svg {
    height: 80%;
    width: 80%;
  }
}
</style>
