<template>
  <div>
    <p v-if="error" class="error">Error: {{ error }}</p>

    <qrcode-stream @decode="onDecode" @init="onInit" />
  </div>
</template>

<script>
import { QrcodeStream } from 'vue-qrcode-reader'
import { mapState } from 'vuex'

export default {
  components: { QrcodeStream },
  data() {
    return {
      result: '',
      error: ''
    }
  },
  computed: { ...mapState('patients', ['formSteps']) },
  methods: {
    onDecode(result) {
      this.result = result

      let patient
      try {
        patient = JSON.parse(result)

        // Validate JSON schema
        const incommingKeys = Object.keys(patient)
        const requiredKeys = [
          'id',
          'firstName',
          'lastName',
          'birthNumber',
          'phoneNumber',
          'answers'
        ]
        requiredKeys.forEach(key => {
          if (incommingKeys.indexOf(key) === -1)
            throw Error(`Error: Missing key "${key}" in JSON`)
        })

        const incommingAnswers = Object.keys(patient.answers)
        const requiredAnswers = this.formSteps
          .map(step => step.order)
          .filter(stepNum => stepNum !== '0' && stepNum.length <= 1)

        requiredAnswers.forEach(answer => {
          if (incommingAnswers.indexOf(answer) === -1)
            throw Error(`Error: Missing answer "${answer}"  in JSON`)
        })

        // Remove keys, we don't need
        Object.keys(patient).forEach(key => {
          if (requiredKeys.indexOf(key) === -1) delete patient[key]
        })

        // Emit valid patient object
        this.$emit('patient', patient)
      } catch (e) {
        this.error = `Error reading QR code! Make sure you are only reading QR codes generated by this app, your (and patient's) app is up to date. Then try again.`
        console.error(e)
      }
    },
    async onInit(promise) {
      try {
        await promise
      } catch (error) {
        if (error.name === 'NotAllowedError') {
          this.error = 'ERROR: you need to grant camera access permisson'
        } else if (error.name === 'NotFoundError') {
          this.error = 'ERROR: no camera on this device'
        } else if (error.name === 'NotSupportedError') {
          this.error = 'ERROR: secure context required (HTTPS, localhost)'
        } else if (error.name === 'NotReadableError') {
          this.error = 'ERROR: is the camera already in use?'
        } else if (error.name === 'OverconstrainedError') {
          this.error = 'ERROR: installed cameras are not suitable'
        } else if (error.name === 'StreamApiNotSupportedError') {
          this.error = 'ERROR: Stream API is not supported in this browser'
        }
      }
    }
  }
}
</script>

<style scoped>
.error {
  font-weight: bold;
  color: red;
}
</style>
